name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'The purpose of this repo is to stand as a record of the Docker project. While we might improve the application its generally not the focus of the maintainers and hence of a lower priority '
        pr-message: 'Great job on taking the pain to improve the code for everyone's benefit. Hang tight and we'll get back to you with improvements if any'
